name: Publish Website

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: dailylivinglife.com
          remote-user: u520196234
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: /home/u520196234/domains/dailylivinglife.com/public_html/wp-content/themes/dll_theme/
